require('btkramm.plugins.lsp')
require('btkramm.plugins.cmp')

require('btkramm.plugins.bufferline')
require('btkramm.plugins.comment')
require('btkramm.plugins.conform')
require('btkramm.plugins.gitsigns')
require('btkramm.plugins.lint')
require('btkramm.plugins.lualine')
require('btkramm.plugins.nvim-autopairs')
require('btkramm.plugins.nvim-surround')
require('btkramm.plugins.nvim-tree')
require('btkramm.plugins.nvim-treesitter')
require('btkramm.plugins.telescope')
